# Generated by Django 5.1.2 on 2025-01-15 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_character__id_alter_character_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='meta',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
